/** A small bundle of public-domain (World English Bible) passages so the reader
 *  works offline / when the Bible API host isn't reachable. Keyed by "Book Chapter". */
import { Verse } from './bible';

export const OFFLINE: Record<string, Verse[]> = {
  'Psalms 23': [
    { verse: 1, text: 'Yahweh is my shepherd; I shall lack nothing.' },
    { verse: 2, text: 'He makes me lie down in green pastures. He leads me beside still waters.' },
    { verse: 3, text: 'He restores my soul. He guides me in the paths of righteousness for his name’s sake.' },
    { verse: 4, text: 'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.' },
    { verse: 5, text: 'You prepare a table before me in the presence of my enemies. You anoint my head with oil. My cup runs over.' },
    { verse: 6, text: 'Surely goodness and loving kindness shall follow me all the days of my life, and I will dwell in Yahweh’s house forever.' },
  ],
  'Psalms 46': [
    { verse: 1, text: 'God is our refuge and strength, a very present help in trouble.' },
    { verse: 2, text: 'Therefore we won’t be afraid, though the earth changes, though the mountains are shaken into the heart of the seas;' },
    { verse: 3, text: 'though its waters roar and are troubled, though the mountains tremble with their swelling. Selah.' },
    { verse: 4, text: 'There is a river, the streams of which make the city of God glad, the holy place of the tents of the Most High.' },
    { verse: 5, text: 'God is in her midst. She shall not be moved. God will help her at dawn.' },
    { verse: 6, text: 'The nations raged. The kingdoms were moved. He lifted his voice and the earth melted.' },
    { verse: 7, text: 'Yahweh of Armies is with us. The God of Jacob is our refuge. Selah.' },
    { verse: 8, text: 'Come, see Yahweh’s works, what desolations he has made in the earth.' },
    { verse: 9, text: 'He makes wars cease to the end of the earth. He breaks the bow, and shatters the spear. He burns the chariots in the fire.' },
    { verse: 10, text: '“Be still, and know that I am God. I will be exalted among the nations. I will be exalted in the earth.”' },
    { verse: 11, text: 'Yahweh of Armies is with us. The God of Jacob is our refuge. Selah.' },
  ],
  'John 3': [
    { verse: 1, text: 'Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews.' },
    { verse: 2, text: 'The same came to him by night, and said to him, “Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do, unless God is with him.”' },
    { verse: 3, text: 'Jesus answered him, “Most certainly I tell you, unless one is born anew, he can’t see God’s Kingdom.”' },
    { verse: 4, text: 'Nicodemus said to him, “How can a man be born when he is old? Can he enter a second time into his mother’s womb, and be born?”' },
    { verse: 5, text: 'Jesus answered, “Most certainly I tell you, unless one is born of water and spirit, he can’t enter into God’s Kingdom.' },
    { verse: 6, text: 'That which is born of the flesh is flesh. That which is born of the Spirit is spirit.' },
    { verse: 7, text: 'Don’t marvel that I said to you, ‘You must be born anew.’' },
    { verse: 8, text: 'The wind blows where it wants to, and you hear its sound, but don’t know where it comes from and where it is going. So is everyone who is born of the Spirit.”' },
    { verse: 9, text: 'Nicodemus answered him, “How can these things be?”' },
    { verse: 10, text: 'Jesus answered him, “Are you the teacher of Israel, and don’t understand these things?' },
    { verse: 11, text: 'Most certainly I tell you, we speak that which we know, and testify of that which we have seen, and you don’t receive our witness.' },
    { verse: 12, text: 'If I told you earthly things and you don’t believe, how will you believe if I tell you heavenly things?' },
    { verse: 13, text: 'No one has ascended into heaven but he who descended out of heaven, the Son of Man, who is in heaven.' },
    { verse: 14, text: 'As Moses lifted up the serpent in the wilderness, even so must the Son of Man be lifted up,' },
    { verse: 15, text: 'that whoever believes in him should not perish, but have eternal life.' },
    { verse: 16, text: 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.' },
    { verse: 17, text: 'For God didn’t send his Son into the world to judge the world, but that the world should be saved through him.' },
    { verse: 18, text: 'He who believes in him is not judged. He who doesn’t believe has been judged already, because he has not believed in the name of the one and only Son of God.' },
    { verse: 19, text: 'This is the judgment, that the light has come into the world, and men loved the darkness rather than the light, for their works were evil.' },
    { verse: 20, text: 'For everyone who does evil hates the light, and doesn’t come to the light, lest his works would be exposed.' },
    { verse: 21, text: 'But he who does the truth comes to the light, that his works may be revealed, that they have been done in God.' },
  ],
};
